### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by deadmouse** [David-Carrasco/Scrapy-Idealista#12]
Estoy recibiendo este error:

```
PS C:\Users\deadmouse\Desktop\Scrapy-Idealista> scrapy crawl idealista -t csv -o pisos.csv
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\deadmouse\AppData\Roaming\Python\Python39\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "C:\Users\deadmouse\AppData\Roaming\Python\Python39\site-packages\scrapy\cmdline.py", line 142, in execute
    _run_print_help(parser, cmd.process_options, args, opts)
  File "C:\Users\deadmouse\AppData\Roaming\Python\Python39\site-packages\scrapy\cmdline.py", line 100, in _run_print_help
    func(*a, **kw)
  File "C:\Users\deadmouse\AppData\Roaming\Python\Python39\site-packages\scrapy\commands\__init__.py", line 133, in process_options
    feeds = feed_process_params_from_cli(
  File "C:\Users\deadmouse\AppData\Roaming\Python\Python39\site-packages\scrapy\utils\conf.py", line 169, in feed_process_params_from_cli
    warnings.warn(message, ScrapyDeprecationWarning, stacklevel=2)
TypeError: expected string or bytes-like object
PS C:\Users\deadmouse\Desktop\Scrapy-Idealista> 
```

¿Cuál podría ser la causa? Gracias

**Comment by mikemajara** [comment]
try `scrapy crawl idealista -o pisos.csv`
