### ISSUE TITLE
Cannot execute code

### ISSUE THREAD

**Issue by sebastianxcf** [David-Carrasco/Scrapy-Idealista#5]
Hi, I'm getting this error when execute "scrapy crawl idealista -o test.csv -t csv" in the root of the project.

Traceback (most recent call last):
  File "/usr/local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "~.local/lib/python2.7/site-packages/scrapy/cmdline.py", line 114, in execute
    settings = get_project_settings()
  File "~/.local/lib/python2.7/site-packages/scrapy/utils/project.py", line 69, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "~/.local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 294, in setmodule
    module = import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "~/Scrapy-Idealista-master/idealista/settings.py", line 11, in <module>
    from .proxies import get_proxies
  File "~/Scrapy-Idealista-master/idealista/proxies/__init__.py", line 1, in <module>
    from .proxies import get_proxies
  File "~/Scrapy-Idealista-master/idealista/proxies/proxies.py", line 1, in <module>
    import requests
ImportError: No module named requests

**Comment by David-Carrasco** [comment]
Did you install the dependencies with **pip install -r requirements.txt**?

BTW, I haven't tested the crawler with python 2.7, try with python 3.X

**Comment by tomekit** [comment]
Thanks for that repo.
I am not complaining, it's just would be good to indicate what Python version is required on the README page. 
For someone (e.g. me) who doesn't have much of a Python background it's not straightforward to recognize what Python version to use, by seeing the `python` or `pip` without the respective version number. There seem to be lots of mess and confusion around Python 2 and 3.

**Comment by David-Carrasco** [comment]
Hi, no worries.
You are right, I'll point out in the README  and requirements file the minimal python version required.

**Comment by David-Carrasco** [comment]
@tomekit #7
